In [68]:
using Pkg # package manager
Pkg.activate(".") # activate the current environment (Project.toml)
Pkg.status() # show the status of the current environment

Status `~/Projects/Lab-CA-SS26/Lab-CA-SS26-resources/Project.toml`
  [cffab07f] GraphNeuralNetworks v1.1.0
⌃ [86223c79] Graphs v1.13.1
  [e79ef3ae] GraphsOptim v0.1.0 `https://github.com/JuliaGraphs/GraphsOptim.jl#main`
  [87dc4568] HiGHS v1.22.2
  [4076af6c] JuMP v1.30.0
Info Packages marked with ⌃ have new versions available and may be upgradable.


  Activating project at `~/Projects/Lab-CA-SS26/Lab-CA-SS26-resources`


# Graphs.jl package

In [69]:
Pkg.add("Graphs") # install the Graphs.jl package

   Resolving package versions...
  No Changes to `~/Projects/Lab-CA-SS26/Lab-CA-SS26-resources/Project.toml`
  No Changes to `~/Projects/Lab-CA-SS26/Lab-CA-SS26-resources/Manifest.toml`


In [70]:
using Graphs # load the Graphs.jl package  

In [71]:
# create a simple graph with 5 vertices and 6 edges
g = DiGraph(5) # create an empty graph with 5 vertices

{5, 0} directed simple Int64 graph

In [72]:
add_edge!(g, 1, 2) # add an edge from vertex 1 to vertex 2
add_edge!(g, 1, 3) # add an edge from vertex 1 to vertex 3
add_edge!(g, 2, 3) # add an edge
g

{5, 3} directed simple Int64 graph

In [73]:
add_vertex!(g) # add a new vertex to the graph
g

{6, 3} directed simple Int64 graph

### Graph properties

In [74]:
println("Number of vertices: ", nv(g)) # number of vertices
println("Number of edges: ", ne(g)) # number of edges
println("Is the graph directed? ", is_directed(g)) # check if the graph is directed

println("Vertices: ", collect(vertices(g))) # list of vertices
println("Edges: ", collect(edges(g))) # list of edges



Number of vertices: 6
Number of edges: 3
Is the graph directed? true
Vertices: [1, 2, 3, 4, 5, 6]
Edges: Graphs.SimpleGraphs.SimpleEdge{Int64}[Edge 1 => 2, Edge 1 => 3, Edge 2 => 3]


### Node and edge properties

In [75]:
println("In-degree of vertex 3: ", indegree(g, 3)) # in-degree of vertex 3
println("Out-degree of vertex 1: ", outdegree(g, 1)) # out-degree of vertex 1

println("Neighbors of vertex 1: ", collect(neighbors(g, 1))) # neighbors of vertex 1

println("Is there an edge from vertex 1 to vertex 2? ", has_edge(g, 1, 2)) # check if there is an edge from vertex 1 to vertex 2
myedges = collect(edges(g)) # get the list of edges
println("Source of edge (1, 2): ", src(myedges[1])) # source of the first edge
println("Destination of edge (1, 2): ", dst(myedges[1])) # destination of the first edge

In-degree of vertex 3: 2
Out-degree of vertex 1: 2
Neighbors of vertex 1: [2, 3]
Is there an edge from vertex 1 to vertex 2? true
Source of edge (1, 2): 1
Destination of edge (1, 2): 2


### Graphs generators
There are many ways to generate random graphs, such as the Erdős–Rényi model, the Barabási–Albert model, and the Watts–Strogatz model. Here are some examples of how to generate random graphs using Graphs.jl:

In [76]:
erdos_renyi(10, 0.3) # generate a random graph with 10 vertices and a probability of 0.3 for edge creation

{10, 12} undirected simple Int64 graph

In [77]:
eug, dists = euclidean_graph(10, 2) # generate a random geometric graph with 10 vertices in 2D space

(SimpleGraph{Int64}(45, [[2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9]]), Dict{Graphs.SimpleGraphs.SimpleEdge{Int64}, Float64}(Edge 7 => 8 => 0.48437435767342685, Edge 7 => 10 => 0.3939179510629892, Edge 8 => 9 => 0.4311270529998967, Edge 4 => 7 => 0.09562195189455319, Edge 1 => 9 => 0.7600856260371591, Edge 2 => 8 => 0.4368327258459063, Edge 2 => 10 => 0.5230361392046701, Edge 3 => 9 => 0.05026860126615038, Edge 4 => 5 => 1.0313378305153678, Edge 1 => 3 => 0.7233709175727021…), [0.8278683407897122 0.20252269620198637 … 0.17843541009888553 0.6594953125390598; 0.4851233143471284 0.0036072173754471137 … 0.09019670414894987 0.2580533429741225])

In [78]:
complete_graph(5) # generate a complete graph with 5 vertices

{5, 10} undirected simple Int64 graph

In [79]:
complete_digraph(5) # generate a complete directed graph with 5 vertices

{5, 20} directed simple Int64 graph

For all the complete list of graph generators and more algorithms, see the [Graphs.jl documentation](https://juliagraphs.org/Graphs.jl/stable).

# Jump.jl package
Jump.jl is a package for mathematical optimization in Julia. It provides a high-level interface for defining and solving optimization problems, including linear programming, integer programming, and nonlinear programming. It supports various solvers, including open-source solvers and commercial solvers like Gurobi and CPLEX.


In [80]:
Pkg.add("JuMP") # install the Jump.jl package
using JuMP # load the Jump.jl package

   Resolving package versions...
  No Changes to `~/Projects/Lab-CA-SS26/Lab-CA-SS26-resources/Project.toml`
  No Changes to `~/Projects/Lab-CA-SS26/Lab-CA-SS26-resources/Manifest.toml`


In [81]:
Pkg.add("HiGHS") # install the HiGHS solver, which is an open-source linear programming solver
using HiGHS # load the HiGHS solver

   Resolving package versions...
  No Changes to `~/Projects/Lab-CA-SS26/Lab-CA-SS26-resources/Project.toml`
  No Changes to `~/Projects/Lab-CA-SS26/Lab-CA-SS26-resources/Manifest.toml`


In [82]:
model = Model(HiGHS.Optimizer) # create a new optimization model using the HiGHS solver
@variable(model, x >= 0) # define a non-negative variable x
@variable(model, y >= 0) # define a non-negative variable y
@objective(model, Max, 3x + 2y) # set the objective function to maximize 3x + 2y
@constraint(model, x + y <= 4) # add a constraint that x + y must be less than or equal to 4
optimize!(model) # solve the optimization problem
assert_is_solved_and_feasible(model)
solution_summary(model)
println("Optimal value: ", objective_value(model)) # print the optimal value of the objective function
println("Optimal x: ", value(x)) # print the optimal value of x
println("Optimal y: ", value(y)) # print the optimal value of y

Running HiGHS 1.13.1 (git hash: 1d267d97c): Copyright (c) 2026 under Apache 2.0 license terms
Using BLAS: blastrampoline 
LP has 1 row; 2 cols; 2 nonzeros
Coefficient ranges:
  Matrix  [1e+00, 1e+00]
  Cost    [2e+00, 3e+00]
  Bound   [0e+00, 0e+00]
  RHS     [4e+00, 4e+00]
Presolving model
1 rows, 1 cols, 1 nonzeros  0s
0 rows, 0 cols, 0 nonzeros  0s
Presolve reductions: rows 0(-1); columns 0(-2); nonzeros 0(-2) - Reduced to empty
Performed postsolve
Solving the original LP from the solution after postsolve

Model status        : Optimal
Objective value     :  1.2000000000e+01
P-D objective error :  0.0000000000e+00
HiGHS run time      :          0.00
Optimal value: 12.0
Optimal x: 4.0
Optimal y: 0.0


For linear programming problems applied to graphs, you can look at the specialized package [GraphsOptim.jl](https://github.com/JuliaGraphs/GraphsOptim.jl).

In [83]:
# given the fact that the repo is experimental you can add it as a local package and then use it
using Pkg; Pkg.add(url="https://github.com/JuliaGraphs/GraphsOptim.jl")

    Updating git-repo `https://github.com/JuliaGraphs/GraphsOptim.jl`
   Resolving package versions...
  No Changes to `~/Projects/Lab-CA-SS26/Lab-CA-SS26-resources/Project.toml`
  No Changes to `~/Projects/Lab-CA-SS26/Lab-CA-SS26-resources/Manifest.toml`


# GraphNeuralNetworks.jl package
GraphNeuralNetworks.jl is a package for graph neural networks in Julia. It provides tools for building and training graph neural networks, which are a type of neural network designed to operate on graph-structured data. 

In [84]:
Pkg.add("GraphNeuralNetworks") # install the GraphNeuralNetworks.jl package
using GraphNeuralNetworks # load the GraphNeuralNetworks.jl package

   Resolving package versions...
  No Changes to `~/Projects/Lab-CA-SS26/Lab-CA-SS26-resources/Project.toml`
  No Changes to `~/Projects/Lab-CA-SS26/Lab-CA-SS26-resources/Manifest.toml`


### Creating a GNNGraph

In [85]:
A = rand(0:1, 10, 10)
g = GNNGraphs.GNNGraph(A)     # from adjacency matrix

GNNGraph:
  num_nodes: 10
  num_edges: 47

In [86]:
adjlist = [[2,3], [1,3], [1,2,4], [3]]
g = GNNGraphs.GNNGraph(adjlist)   # from adjacency list

GNNGraph:
  num_nodes: 4
  num_edges: 8

In [87]:
source = [1,1,2,2,3,3,3,4]
target = [2,3,1,3,1,2,4,3]
g = GNNGraphs.GNNGraph(source, target)    # from COO representation

GNNGraph:
  num_nodes: 4
  num_edges: 8

In [88]:
source = [1, 1, 2, 2, 3, 3]
target = [2, 3, 1, 3, 1, 2]
weight = [1.0, 0.5, 2.1, 2.3, 4, 4.1]
g = GNNGraphs.GNNGraph(source, target, weight)   # from COO representation with weights

GNNGraph:
  num_nodes: 3
  num_edges: 6

##### Integration with Graphs.jl

In [89]:
gd = Graphs.erdos_renyi(10, 20, is_directed=true)

{10, 20} directed simple Int64 graph

In [90]:
GNNGraphs.GNNGraph(gd)

GNNGraph:
  num_nodes: 10
  num_edges: 20

### Creating random GNNGraph and adding features

In [91]:
g = GNNGraphs.rand_graph(10,60)

GNNGraph:
  num_nodes: 10
  num_edges: 60

In [92]:
# add features after construction of the graph
g.ndata.x = rand(3,10); # add node features x
g.edata.e = rand(2,60); # add edge features e
g.gdata.g = rand(1,1);  # add graph features g

In [93]:
g #summary of the graph

GNNGraph:
  num_nodes: 10
  num_edges: 60
  ndata:
    x = 3×10 Matrix{Float64}
  edata:
    e = 2×60 Matrix{Float64}
  gdata:
    g = 1×1 Matrix{Float64}

In [94]:
# add node features during construction of the graph
g2 = GNNGraphs.rand_graph(10,60, ndata = (x = rand(2,10), y = rand(3,10)))

GNNGraph:
  num_nodes: 10
  num_edges: 60
  ndata:
    y = 3×10 Matrix{Float64}
    x = 2×10 Matrix{Float64}

### Message passing

In [95]:
g = GNNGraphs.rand_graph(10,20)
g.ndata.x = ones(1,10)
GNNlib.propagate((xi,xj,e) -> xi.+1, g, +, xi = g.ndata.x) 
# xi.+1 is the message function, + is the aggregation function and xi = g.ndata.x is the initial node feature

1×10 Matrix{Float64}:
 6.0  0.0  4.0  6.0  2.0  2.0  0.0  8.0  6.0  6.0

In [ ]:
g.graph # coo representation of the graph

([8, 6, 1, 4, 8, 3, 1, 4, 9, 1, 10, 8, 4, 10, 9, 5, 3, 9, 10, 8], [10, 8, 4, 10, 9, 5, 3, 9, 10, 8, 8, 6, 1, 4, 8, 3, 1, 4, 9, 1], nothing)

The message passing procedure is the core of graph neural networks. It consists of three steps: message computation, message aggregation, and node update.
The `GraphNeuralNetworks.jl` propagate functtion implements the message computation and aggregation steps, which is then composed by `gather` and `scatter` functions. 

In [104]:
g.ndata.x # the node features 

1×10 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [100]:
messages = GNNlib.gather(g.ndata.x, g.graph[1]) # gather the node features of the neighbors of each node

1×20 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [101]:
message_function(x) = x + 1 # define a message function that adds 1 to the input
messages = message_function.(messages) # apply the message function to the gathered messages

1×20 Matrix{Float64}:
 2.0  2.0  2.0  2.0  2.0  2.0  2.0  2.0  …  2.0  2.0  2.0  2.0  2.0  2.0  2.0

In [ ]:
new_messages = GNNlib.scatter(+, messages, g.graph[2]) # scatter the messages back to the nodes using the aggregation function +

1×10 Matrix{Float64}:
 6.0  0.0  4.0  6.0  2.0  2.0  0.0  8.0  6.0  6.0

## Some references for GraphNeuralNetworks.jl package
- Slides are available at the following link: https://docs.google.com/presentation/d/1_A9QpTp1WaAYojwB6a8_hV5L4cKwKrgnr12c9AslZZs/edit?usp=sharing
- Other more recent slides are available at the following link: https://docs.google.com/presentation/d/1ocgJj5jGwaa2fCtpL3GwlCl2zlS8MuTkS_P68gwuoAQ/edit?usp=sharing
- Last JuliaCon 2025 talk on GraphNeuralNetworks.jl: https://www.youtube.com/watch?v=OKpY4gEqJKk&t=652s